global:
  scrape_interval: 60s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]

    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/ssl_targets.json'
        refresh_interval: 1m

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
