groups:
  - name: ssl-certs
    rules:
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "SSL cert for {{ $labels.instance }} expires soon"
          description: "Cert for {{ $labels.instance }} expires in < 30 days."
